export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const ADD_PROFILE_START = 'ADD_PROFILE_START';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL';
export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const ADD_FOODS_HISTORY_START = 'ADD_FOODS_HISTORY_START';
export const ADD_FOODS_HISTORY_SUCCESS = 'ADD_FOODS_HISTORY_SUCCESS';
export const ADD_FOODS_HISTORY_FAIL = 'ADD_FOODS_HISTORY_FAIL';
export const ADD_FOODS_HISTORY_BULK_START = 'ADD_FOODS_HISTORY_BULK_START';
export const ADD_FOODS_HISTORY_BULK_SUCCESS = 'ADD_FOODS_HISTORY_BULK_SUCCESS';
export const ADD_FOODS_HISTORY_BULK_FAIL = 'ADD_FOODS_HISTORY_BULK_FAIL';
export const REMOVE_FOOD_HISTORY_START = 'REMOVE_FOOD_HISTORY_START';
export const REMOVE_FOOD_HISTORY_SUCCESS = 'REMOVE_FOOD_HISTORY_SUCCESS';
export const REMOVE_FOOD_HISTORY_FAIL = 'REMOVE_FOOD_HISTORY_FAIL';

export const ADD_FOOD_START = 'ADD_FOOD_START';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAIL = 'ADD_FOOD_FAIL';
export const FETCH_FOODS_START = 'FETCH_FOODS_START';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAIL = 'FETCH_FOODS_FAIL';

export const ADD_GOAL_START = 'ADD_GOAL_START';
export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const ADD_GOAL_FAIL = 'ADD_GOAL_FAIL';
export const FETCH_GOAL_START = 'FETCH_GOAL_START';
export const FETCH_GOAL_SUCCESS = 'FETCH_GOAL_SUCCESS';
export const FETCH_GOAL_FAIL = 'FETCH_GOAL_FAIL';

export const ADD_MEAL_START = 'ADD_MEAL_START';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAIL = 'ADD_MEAL_FAIL';
export const REMOVE_MEAL_START = 'REMOVE_MEAL_START';
export const REMOVE_MEAL_SUCCESS = 'REMOVE_MEAL_SUCCESS';
export const REMOVE_MEAL_FAIL = 'REMOVE_MEAL_FAIL';

export const ADD_QUICK_CALORIES_START = 'ADD_QUICK_CALORIES_START';
export const ADD_QUICK_CALORIES_SUCCESS = 'ADD_QUICK_CALORIES_SUCCESS';
export const ADD_QUICK_CALORIES_FAIL = 'ADD_QUICK_CALORIES_FAIL';
export const REMOVE_QUICK_CALORIES_START = 'REMOVE_QUICK_CALORIES_START';
export const REMOVE_QUICK_CALORIES_SUCCESS = 'REMOVE_QUICK_CALORIES_SUCCESS';
export const REMOVE_QUICK_CALORIES_FAIL = 'REMOVE_QUICK_CALORIES_FAIL';
